title: Cesar's Ramirez CIT_480 Blog 2

logo: /assets/img/apache_server.png
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
